---
# file: host_vars/localhost

ansible_connection: local

names:
  - Westley
  - The Dread Pirate Roberts
  - Inigo Montoya
  - Prince Humperdinck
  - Count Tyrone Rugen
  - Vizzini
  - Fezzik
  - The Grandson
  - The Princess Bride
  - The Grandfather / Narrator
  - The Impressive Clergyman
  - The Albino
  - Valerie
  - Miracle Max